# Generated by Django 4.2.25 on 2026-04-21 00:45

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='FeatureEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_embedding', to='voting.feature')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='feature_embedding_cosine_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
